// Generates packages/contracts/src/lib/Poseidon2.sol (BN254 Poseidon2, t=4, d=5, 8 full + 56
// partial rounds) and packages/contracts/src/privacy/PoolZeros.sol (empty-subtree values of the
// shielded pool tree) from the constants of @zkpassport/poseidon2, which match Barretenberg's
// poseidon2_params.hpp and noir-lang/poseidon v0.4.0 `Poseidon2::hash`.
//
// Bit-compatibility with Noir/bb is NOT assumed: it is proven by
//   - packages/zk/circuits/shielded_withdraw (nargo test: Noir outputs == the vectors below)
//   - packages/contracts/test/privacy/Poseidon2.t.sol (Solidity == the same vectors, and ==
//     bb.js + @zkpassport/poseidon2 for random inputs via FFI)
//
//   node packages/attest-core/scripts/gen-poseidon2-sol.ts
import { writeFile } from "node:fs/promises";
import { keccak256, toBytes } from "viem";
import { MAT_DIAG4_M_1, RC4 } from "../node_modules/@zkpassport/poseidon2/dist/esm/bn254/constants.js";
import { poseidon2, FIELD_MODULUS } from "../src/poseidon.ts";
import { POOL_DEPTH, POOL_ZERO_VALUE, poolZeros } from "../src/pool.ts";

const P = FIELD_MODULUS;
const hex = (x: bigint) => `0x${x.toString(16).padStart(64, "0")}`;
if (RC4.length !== 64) throw new Error("expected 64 rounds");
if (POOL_ZERO_VALUE !== BigInt(keccak256(toBytes("kakushi.pool.zero"))) % P) throw new Error("zero value drift");

const D = MAT_DIAG4_M_1.map(hex);
const I = "            ";
const sbox = (v: string) => [`${I}{`, `${I}    let x2 := mulmod(${v}, ${v}, p)`, `${I}    ${v} := mulmod(mulmod(x2, x2, p), ${v}, p)`, `${I}}`];
// external matrix M4 = [[5,7,1,3],[4,6,1,1],[1,3,5,7],[1,1,4,6]] (bb matrix_multiplication_4x4); inputs < P
const ext = [
  `${I}{`,
  `${I}    let t0 := addmod(s0, s1, p)`,
  `${I}    let t1 := addmod(s2, s3, p)`,
  `${I}    let t2 := add(add(s1, s1), t1)`,
  `${I}    let t3 := add(add(s3, s3), t0)`,
  `${I}    s3 := addmod(shl(2, t1), t3, p)`,
  `${I}    s1 := addmod(shl(2, t0), t2, p)`,
  `${I}    s0 := addmod(t3, s1, p)`,
  `${I}    s2 := addmod(t2, s3, p)`,
  `${I}}`,
].join("\n");
const rounds: string[] = [`${I}// initial linear layer`, ext];
for (let r = 0; r < 64; r++) {
  const rc = RC4[r]!.map(hex);
  if (r < 4 || r >= 60) {
    rounds.push(`${I}// full round ${r}`);
    for (let i = 0; i < 4; i++) {
      rounds.push(`${I}s${i} := addmod(s${i}, ${rc[i]}, p)`, ...sbox(`s${i}`));
    }
    rounds.push(ext);
  } else {
    rounds.push(
      `${I}// partial round ${r}`,
      `${I}s0 := addmod(s0, ${rc[0]}, p)`,
      ...sbox("s0"),
      `${I}{`,
      `${I}    let t := add(add(s0, s1), add(s2, s3))`,
      `${I}    s0 := addmod(mulmod(s0, d0, p), t, p)`,
      `${I}    s1 := addmod(mulmod(s1, d1, p), t, p)`,
      `${I}    s2 := addmod(mulmod(s2, d2, p), t, p)`,
      `${I}    s3 := addmod(mulmod(s3, d3, p), t, p)`,
      `${I}}`,
    );
  }
}

const poseidon = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// GENERATED by packages/attest-core/scripts/gen-poseidon2-sol.ts. Do not edit by hand.

/// @notice Poseidon2 over the BN254 scalar field (t = 4, d = 5, 8 full + 56 partial rounds),
///         bit-compatible with noir-lang/poseidon v0.4.0 \`Poseidon2::hash(input, len)\` and
///         Barretenberg's poseidon2 (sponge: rate 3, capacity 1, IV = len << 64).
/// @dev    Inputs are taken mod P (hash(x) == hash(x mod P)); callers that need canonical
///         field elements must check \`x < P\` themselves.
library Poseidon2 {
    uint256 internal constant P = ${hex(P)};

    /// Noir: Poseidon2::hash([x], 1)
    function hash1(uint256 x) internal pure returns (uint256 r) {
        (r,,,) = permute(x, 0, 0, 1 << 64);
    }

    /// Noir: Poseidon2::hash([a, b], 2)
    function hash2(uint256 a, uint256 b) internal pure returns (uint256 r) {
        (r,,,) = permute(a, b, 0, 2 << 64);
    }

    /// Noir: Poseidon2::hash([a, b, c], 3)
    function hash3(uint256 a, uint256 b, uint256 c) internal pure returns (uint256 r) {
        (r,,,) = permute(a, b, c, 3 << 64);
    }

    /// Noir: Poseidon2::hash(xs, xs.len()) for any length (fixed-length sponge).
    function hash(uint256[] memory xs) internal pure returns (uint256) {
        uint256 n = xs.length;
        uint256 s0;
        uint256 s1;
        uint256 s2;
        uint256 s3 = n << 64;
        if (n == 0) {
            (s0,,,) = permute(0, 0, 0, s3);
            return s0;
        }
        for (uint256 i; i < n; i += 3) {
            s0 = addmod(s0, xs[i], P);
            if (i + 1 < n) s1 = addmod(s1, xs[i + 1], P);
            if (i + 2 < n) s2 = addmod(s2, xs[i + 2], P);
            (s0, s1, s2, s3) = permute(s0, s1, s2, s3);
        }
        return s0;
    }

    /// The Poseidon2 permutation (Barretenberg poseidon2_permutation.hpp).
    function permute(uint256 a, uint256 b, uint256 c, uint256 d)
        internal
        pure
        returns (uint256, uint256, uint256, uint256)
    {
        // The state, P and the internal-matrix diagonal pass through scratch memory above the free
        // memory pointer (never allocated), so the main block references no Solidity variables
        // and P / diag stay on the stack: with literals, the legacy optimizer (runs = 200) turns the
        // repeated 32-byte constants into CODECOPY loads, which roughly doubles the gas.
        assembly ("memory-safe") {
            let m := mload(0x40)
            mstore(m, a)
            mstore(add(m, 0x20), b)
            mstore(add(m, 0x40), c)
            mstore(add(m, 0x60), d)
            mstore(add(m, 0x80), P)
            mstore(add(m, 0xa0), ${D[0]})
            mstore(add(m, 0xc0), ${D[1]})
            mstore(add(m, 0xe0), ${D[2]})
            mstore(add(m, 0x100), ${D[3]})
        }
        assembly ("memory-safe") {
            let m := mload(0x40)
            let p := mload(add(m, 0x80))
            let d0 := mload(add(m, 0xa0))
            let d1 := mload(add(m, 0xc0))
            let d2 := mload(add(m, 0xe0))
            let d3 := mload(add(m, 0x100))
            let s0 := mod(mload(m), p)
            let s1 := mod(mload(add(m, 0x20)), p)
            let s2 := mod(mload(add(m, 0x40)), p)
            let s3 := mod(mload(add(m, 0x60)), p)
${rounds.join("\n")}
            mstore(m, s0)
            mstore(add(m, 0x20), s1)
            mstore(add(m, 0x40), s2)
            mstore(add(m, 0x60), s3)
        }
        assembly ("memory-safe") {
            let m := mload(0x40)
            a := mload(m)
            b := mload(add(m, 0x20))
            c := mload(add(m, 0x40))
            d := mload(add(m, 0x60))
        }
        return (a, b, c, d);
    }
}
`;

const zeros = poolZeros();
if (zeros.length !== POOL_DEPTH + 1) throw new Error("zeros length");
const cases = zeros.map((z, i) => `            case ${i} { z := ${hex(z)} }`).join("\n");
const zerosSol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// GENERATED by packages/attest-core/scripts/gen-poseidon2-sol.ts. Do not edit by hand.

/// @notice Empty-subtree values of the KakushiPool Merkle tree (depth ${POOL_DEPTH}).
///         zeros(0) = uint256(keccak256("kakushi.pool.zero")) % P (the empty leaf);
///         zeros(i + 1) = Poseidon2.hash2(zeros(i), zeros(i)); zeros(${POOL_DEPTH}) = root of the empty tree.
library PoolZeros {
    uint256 internal constant DEPTH = ${POOL_DEPTH};
    uint256 internal constant ZERO_VALUE = ${hex(zeros[0]!)};

    function zeros(uint256 i) internal pure returns (uint256 z) {
        assembly ("memory-safe") {
            switch i
${cases}
            default { revert(0, 0) }
        }
    }
}
`;

// a few fixed vectors, also asserted by the Noir tests and Poseidon2.t.sol
const vectors: [bigint[], bigint][] = [
  [[1n], poseidon2([1n])],
  [[1n, 2n], poseidon2([1n, 2n])],
  [[0n, 0n], poseidon2([0n, 0n])],
  [[1n, 2n, 3n], poseidon2([1n, 2n, 3n])],
  [[P - 1n, P - 2n], poseidon2([P - 1n, P - 2n])],
  [[1n, 2n, 3n, 4n, 5n], poseidon2([1n, 2n, 3n, 4n, 5n])],
];

const root = new URL("../../contracts/src/", import.meta.url);
await writeFile(new URL("lib/Poseidon2.sol", root), poseidon);
await writeFile(new URL("privacy/PoolZeros.sol", root), zerosSol);
process.stderr.write("wrote src/lib/Poseidon2.sol and src/privacy/PoolZeros.sol\nvectors:\n");
for (const [i, o] of vectors) process.stderr.write(`  [${i.map(hex).join(", ")}] -> ${hex(o)}\n`);
