// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// GENERATED by packages/attest-core/scripts/gen-poseidon2-sol.ts. Do not edit by hand.

/// @notice Empty-subtree values of the KakushiPool Merkle tree (depth 20).
///         zeros(0) = uint256(keccak256("kakushi.pool.zero")) % P (the empty leaf);
///         zeros(i + 1) = Poseidon2.hash2(zeros(i), zeros(i)); zeros(20) = root of the empty tree.
library PoolZeros {
    uint256 internal constant DEPTH = 20;
    uint256 internal constant ZERO_VALUE = 0x25b050981509767925e5c4a83dbd420549c32b744ac3ee76ed7e9d6fd2c0d8d4;

    function zeros(uint256 i) internal pure returns (uint256 z) {
        assembly ("memory-safe") {
            switch i
            case 0 { z := 0x25b050981509767925e5c4a83dbd420549c32b744ac3ee76ed7e9d6fd2c0d8d4 }
            case 1 { z := 0x09647c749e77d091230a1ca796d58b2e0def955287637370cd35f5c933133c4b }
            case 2 { z := 0x05ad4126d3be1ac006115cac2baabe75041be57eb616e4acc6b2e15dfbd18b72 }
            case 3 { z := 0x215aa52287484aaa32e979102a15ba14e6c218f8f433bcaa5b271b7d3e9cb34e }
            case 4 { z := 0x037389981dea1db351c4bb91fb07df07b854cf77782f6d3bf581fd325f2c2249 }
            case 5 { z := 0x24595f3d026350a3164856cb77c9b1becd13b30763fb9a8f8b0e31490f36f8d1 }
            case 6 { z := 0x014719ea57249dabc58b1f71f8950caf4eb516ff00118bf1f1e60ccdd20b5949 }
            case 7 { z := 0x23e705a4d1a4ce1a359de8eff854d5aaebdde59cde8e29c03b37eb274e865d9f }
            case 8 { z := 0x18939e06bacfab7057492310f50033e627f3232787cf119a90579d39df3f25e6 }
            case 9 { z := 0x20d7de90e860c5f06c1939f4d47328fedbdb18f6cd48becd29432568a7907d5e }
            case 10 { z := 0x04ef1341d75801a30c722c74a10da63eb000a9a07ad66d842efbdb9a9eeaadcc }
            case 11 { z := 0x29e3ba956ea8669d1c5481594494477e150118ed72f74c90c779f0a3077d4e64 }
            case 12 { z := 0x0cac40fa71f853f9407dea6b9499f20987bd6c52ebb7442b9eea9ec9f90700c4 }
            case 13 { z := 0x05901ca9ea3d48e04383fa8e5f7427a163b23db0966ab11f5b82ac4a05509120 }
            case 14 { z := 0x076e9929276d8cf4f4b4571351eb00780fe191b05205d9fab7e7c11a7671c44a }
            case 15 { z := 0x01542a538d4107199c59d8b68bacd24d3fe9fe475368f1516825698f96310688 }
            case 16 { z := 0x19be5a0ea2b27e08d642a8ffe8fe557ed7619e309dfa01a7711e1c2c00e25425 }
            case 17 { z := 0x0c589596f4aff69008e7a9a145751283d1aaedebe65e60689a38c990778bf5e5 }
            case 18 { z := 0x029b7265da3ee353acb4001c0a4f255a2f447c069377a6c4f0a528a99ff93dc6 }
            case 19 { z := 0x2ddf3d2604566c6ec494784f7efbb229fd15f955552927e7d261d74a9affb4a3 }
            case 20 { z := 0x286a0baf08ac2d1d9f56281cafab9d2a32be3b0ba413f3b4902aacb0819e3757 }
            default { revert(0, 0) }
        }
    }
}
