// Generates packages/sdk/src/abi.ts from Foundry artifacts (packages/contracts/out).
import { readFileSync, writeFileSync } from "node:fs";

const contracts = ["EBC", "MDC", "AttestationOracle", "DisputeModule", "PayoutRouter", "SourceRouter", "Errors"];
let out = "// GENERATED by scripts/gen-abi.ts from packages/contracts/out. Do not edit.\n\n";
for (const c of contracts) {
  const j = JSON.parse(readFileSync(`packages/contracts/out/${c}.sol/${c}.json`, "utf8"));
  const name = c === "Errors" ? "errorsAbi" : `${c[0]!.toLowerCase()}${c.slice(1)}Abi`.replace(/^eBCAbi$/, "ebcAbi").replace(/^mDCAbi$/, "mdcAbi");
  out += `export const ${name} = ${JSON.stringify(j.abi)} as const;\n\n`;
}
out += `export const erc20Abi = ${JSON.stringify([
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "a", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "a", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }], anonymous: false },
])} as const;\n\n`;
out += `export const aggregatorAbi = ${JSON.stringify([
  { type: "function", name: "latestRoundData", stateMutability: "view", inputs: [], outputs: [{ name: "roundId", type: "uint80" }, { name: "answer", type: "int256" }, { name: "startedAt", type: "uint256" }, { name: "updatedAt", type: "uint256" }, { name: "answeredInRound", type: "uint80" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
])} as const;\n\n`;
out += `export const forwarderAbi = ${JSON.stringify([
  { type: "function", name: "report", stateMutability: "nonpayable", inputs: [{ name: "receiver", type: "address" }, { name: "rawReport", type: "bytes" }, { name: "reportContext", type: "bytes" }, { name: "signatures", type: "bytes[]" }], outputs: [] },
  { type: "event", name: "ReportProcessed", inputs: [{ name: "receiver", type: "address", indexed: true }, { name: "workflowExecutionId", type: "bytes32", indexed: true }, { name: "reportId", type: "bytes2", indexed: true }, { name: "result", type: "bool", indexed: false }], anonymous: false },
])} as const;\n`;
writeFileSync("packages/sdk/src/abi.ts", out);
console.log("wrote packages/sdk/src/abi.ts");
